version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - logstash  # Dependencia de Logstash
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tu_base_datos
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=contraseña

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: tu_base_datos
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  elasticsearch:
    build: elk/elasticsearch/
    container_name: elasticsearch
    restart: always
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
      XPACK_MONITORING_ENABLED: false
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      network.host: "0.0.0.0"
  
  kibana:
    build: elk/kibana/
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    
  logstash:
    build: elk/logstash/
    container_name: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/config/:/etc/logstash/conf.d
    ports:
      - "9999:9999"
    depends_on:
      - elasticsearch

