name: Java CI

on:
  push:
    branches:
      - main  # Cambia 'main' si tu rama principal tiene otro nombre
  pull_request:
    branches:
      - main  # Cambia 'main' si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
